ekf_filter_node:
  ros__parameters:
    frequency: 10.0  # Keep up with IMU
    sensor_timeout: 0.15
    two_d_mode: true # locks 

    # Visual odometry — use only twist (velocity), ignore pose
    odom0: /odom
    odom0_config: [false, false, false, # xyz pose
                   false, false, false, # rpy pose
                   true, true, false,   # linear velocity 
                   false, false, true,  # angular velocity
                   false, false, false] # linear acceleration
    odom0_differential: false
    odom0_relative: false

    # IMU — use only angular velocity and yaw orientation
    imu0: /imu
    imu0_config: [false, false, false, # xyz pose
                  false, false, true,  # rpy pose
                  false, false, false, # linear velocity
                  false, false, true,  # angular velocity (rpy)
                  true, true, false]   # linear acceleration
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # Frame settings
    world_frame: odom
    base_link_frame: base_link
    odom_frame: odom
    map_frame: map
    publish_tf: false

    # x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az