ekf_filter_node:
  ros__parameters:
    frequency: 40.0 # 30–50 Hz to kepe up with 100 hz imu
    sensor_timeout: 0.15 # Rule of thumb: sensor_timeout ≈ 2–3x max sensor period, cam running at 15 hz -> 0.067s period
    two_d_mode: true

    odom0: /odom
    odom0_config: [false, false, false,
                   true,  true,  true,
                   false, false, false,
                   false, false, false, 
                   false, false, false]
    odom0_differential: false

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true, true, true, 
                  true, true, true]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    world_frame: odom
    base_link_frame: base_link
    odom_frame: odom
    map_frame: map
    publish_tf: true


  # [ x,  y,  z,          position
  # roll, pitch, yaw,     orientation
  # vx, vy, vz,           linear velocity
  # vroll, vpitch, vyaw,  angular velocity
  # ax, ay, az ]          linear acceleration
  # x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
