ekf_filter_node:
  ros__parameters:

    frequency: 40.0
    sensor_timeout: 0.15
    two_d_mode: true  # If your robot is ground-based and planar. Set to false for full 3D.

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    map_frame: map
    world_frame: odom
    base_link_frame: base_link
    odom_frame: odom
    publish_tf: true

    # # Process noise covariance (state estimate uncertainty)
    # process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
    #                            0, 0.05, 0, 0, 0, 0,
    #                            0, 0, 0.01, 0, 0, 0,
    #                            0, 0, 0, 0.1, 0, 0,
    #                            0, 0, 0, 0, 0.1, 0,
    #                            0, 0, 0, 0, 0, 0.1]

    # initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0,
    #                               0, 1e-9, 0, 0, 0, 0,
    #                               0, 0, 1e-9, 0, 0, 0,
    #                               0, 0, 0, 1e-9, 0, 0,
    #                               0, 0, 0, 0, 1e-9, 0,
    #                               0, 0, 0, 0, 0, 1e-9]

    # # Use IMU covariances directly
    # use_control_covariance: false
