ekf_filter_node:
  ros__parameters:
    frequency: 40.0  # Keep up with IMU
    sensor_timeout: 0.15
    two_d_mode: true

    # Visual odometry — use only twist (velocity), ignore pose
    odom0: /odom
    odom0_config: [false, false, false,  # position (x, y, z)
                   true,  true,  true,   # angular velocity (roll, pitch, yaw)
                   false, false, false, # velocity (x, y, z) — disabled for 2D mode
                   false, false, false, # orientation (roll, pitch, yaw)
                   false, false, false] # linear acceleration (x, y, z)
    odom0_differential: true
    odom0_relative: true

    # IMU — use only angular velocity and yaw orientation
    imu0: /imu
    imu0_config: [false, false, false,  # position
                  true,  true,  true,   # angular velocity
                  false, false, false, # linear velocity
                  false, false, true,  # orientation (only yaw)
                  false, false, false] # linear acceleration
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # Frame settings
    world_frame: odom
    base_link_frame: base_link
    odom_frame: odom
    map_frame: map
    publish_tf: true
