mpu9250driver_node:
  ros__parameters:
    frequency: 100

    # IMU configuration
    gyro_range: 0              # ±250°/s
    accel_range: 0             # ±2g
    dlpf_bandwidth: 2          # ~94 Hz filter cutoff

    # Offset values (overwritten by calibration if below is true)
    gyro_x_offset: 0.0         # [deg/s]
    gyro_y_offset: 0.0         # [deg/s]
    gyro_z_offset: 0.0         # [deg/s]
    accel_x_offset: 0.0        # [m/s²]
    accel_y_offset: 0.0        # [m/s²]
    accel_z_offset: 0.0        # [m/s²]

    calibrate: true            # Run bias calibration at startup
