rtabmap_odom:
  ros__parameters:
    frame_id: "base_link"  # Robot's body frame
    odom_frame_id: "odom"  # Output odometry frame
    subscribe_stereo: true
    approx_sync: true
    queue_size: 30

    # # Optional but useful for tuning
    # stereo_from_depth: false
    # stereo_fx: 0.0  # Overwritten by camera_info
    # stereo_baseline: 0.0  # Overwritten by camera_info

    # Filtering / Motion model
    wait_for_transform: true
    wait_imu_to_init: false  # set to true if using IMU initialization

    # Visualization/debugging
    publish_tf: false
    publish_null_when_lost: true
