rtabmap_odom:
  ros__parameters:
    frame_id: "base_link"  # Robot's body frame
    odom_frame_id: "odom"  # Output odometry frame
    subscribe_stereo: true
    approx_sync: true
    queue_size: 3
    approx_sync_max_interval: 0.02

    Rtabmap/LoggerLeve: "3"

    # Odometry tuning
    Vis/MinInliers: "20"
    Odom/Strategy: "0"
    Odom/MaxGuessDistance: "0.3"
    StereoEgoMotion/MaxTranslation: "0.3"

    Odom/FilteringStrategy: "0"
    Odom/FilterSmoothFactor: "0.1"  # Higher trust in predicted motion
    # Odom/GuessMotion: "true"        # Predict motion from past velocity

    publish_tf: false
    publish_null_when_lost: true

    # # Optional but useful for tuning
    # stereo_from_depth: false
    # stereo_fx: 0.0  # Overwritten by camera_info
    # stereo_baseline: 0.0  # Overwritten by camera_info

    # Filtering / Motion model
    # wait_for_transform: false
    wait_imu_to_init: false  # set to true if using IMU initialization

    # Visualization/debugging
    # publish_tf: false
    # publish_null_when_lost: true

    Odom/MaxFeatures: "500"
    Odom/MinInliers: "20"
    Odom/FeatureType: "ORB"  # Try SURF or SIFT if CPU permits
    