stereo_cam_node:
  ros__parameters:
    resolution_preset: "1080p"
    frame_rate: 30
    imu_rate: 100
    frame_id: "stereo_camera_base"
    left_camera_frame: "left_camera_frame"
    right_camera_frame: "right_camera_frame"
    imu_frame: "imu_link"
    camera_info_url: 
      left: "file:///$(find stereo_cam)/config/left_camera.yaml"
      right: "file:///$(find stereo_cam)/config/right_camera.yaml"
    exposure_mode: "normal"
    gain: 1.0
    exposure_time: 0  # 0 for auto 