disparity_node:
  ros__parameters:
    approximate_sync:         'True'
    stereo_algorithm:         '1'
    prefilter_size:           '5'
    prefilter_cap:            '31'
    correlation_window_size:  '5'
    min_disparity:            '0'
    disparity_range:          '64'
    texture_threshold:        '5'
    speckle_size:             '50'
    speckle_range:            '2'
    disp12_max_diff:          '1'
    uniqueness_ratio:         '10.0'
    P1:                       '200.0'
    P2:                       '800.0'
    sgbm_mode:                '2'


# name='approximate_sync', default_value='True',
# description='Whether to use approximate synchronization of topics. Set to true if '
#             'the left and right cameras do not produce exactly synced timestamps.'

# name='stereo_algorithm', default_value='1',
# description='Stereo algorithm: Block Matching (0) or Semi-Global Block Matching (1)'

# name='prefilter_size', default_value='9',
# description='Normalization window size in pixels (must be odd)'

# name='prefilter_cap', default_value='31',
# description='Bound on normalized pixel values'

# name='correlation_window_size', default_value='15',
# description='SAD correlation window width in pixels (must be odd)'

# name='min_disparity', default_value='0',
# description='Disparity to begin search at in pixels'

# name='disparity_range', default_value='64',
# description='Number of disparities to search in pixels (must be a multiple of 16)'

# name='texture_threshold', default_value='10',
# description='Filter out if SAD window response does not exceed texture threshold'

# name='speckle_size', default_value='100',
# description='Reject regions smaller than this size in pixels'

# name='speckle_range', default_value='2',
# description='Maximum allowed difference between detected disparities'

# name='disp12_max_diff', default_value='0',
# description='Maximum allowed difference in the left-right disparity check in pixels '
#             '(Semi-Global Block Matching only)'

# name='uniqueness_ratio', default_value='15.0',
# description='Filter out if best match does not sufficiently exceed the next-best match'

# name='P1', default_value='200.0',
# description='The first parameter ccontrolling the disparity smoothness '
#             '(Semi-Global Block Matching only)'

# name='P2', default_value='800.0',
# description='The second parameter ccontrolling the disparity smoothness '
#             '(Semi-Global Block Matching only)'

# name='sgbm_mode', default_value='2',
# description='The mode of the SGBM matcher to be used'

