stereo_node:
  ros__parameters:
    enable_depth: false

    image_width: 640
    image_height: 480
    frame_rate: 120

    # The below must align, or there will be a problem with reading the node
    # - gst_pixel_format: OpenCV Raw Video Media Types. https://gstreamer.freedesktop.org/documentation/additional/design/mediatype-video-raw.html?gi-language=c
    # - it_pixel_format:  OpenCV Image Encodings for Image Transport. https://docs.ros.org/en/electric/api/sensor_msgs/html/namespacesensor__msgs_1_1image__encodings.html
    # - BGR Worked best, another pair would be "GRAY8" and "mono8"
    gst_pixel_format: BGR
    it_pixel_format: bgr8
    
    left_device_file: /dev/video4
    left_payload_type: MJPG

    right_device_file: /dev/video2
    right_payload_type: MJPG
    
    frame_id: "camera_link"
    calibration_file: "package://stereo_cam/config/calibrations/StereoCalibration_7_2_flipped.yaml"