stereo_node:
  ros__parameters:
    enable_depth: false

    image_width: 640
    image_height: 360
    frame_rate: 30

    left_format: MJPG
    left_port: /dev/video0
    left_device: Raspi

    right_format: MJPG
    right_port: /dev/video4
    right_device: Raspi
    
    imu_rate: 100
    
    frame_id: "camera_link"
    left_camera_optical_frame: "left_camera_optical_frame"
    right_camera_optical_frame: "right_camera_optical_frame"
    imu_frame: "imu_link"
    exposure_mode: "normal"
    gain: 1.0
    exposure_time: 0  # 0 for auto
    left_camera_info_url: "package://stereo_cam/config/cameras/left_camera_info.yaml"
    right_camera_info_url: "package://stereo_cam/config/cameras/right_camera_info.yaml"
    # calibration_file: "package://stereo_cam/config/calibrations/StereoCalibration_7_2_flipped.yaml"
    calibration_file: "package://stereo_cam/config/calibrations/StereoCalibration_7_15_laser.yaml"

  
    stereo:
      baseline: 0.152  # 152.4 mm between cameras
      focal_length: 479.14 # pixels
      principal_point: [968.0, 548.5]  # pixels 
